### ISSUE TITLE
text part in the black theme is not visible

### ISSUE THREAD

**Issue by OmlineEditor** [itkach/aard2-android#130]
the default text part in the black theme is not visible. if you select the text then the text is visible

![1](https://user-images.githubusercontent.com/13348933/147277641-3234495c-301d-44e1-aff4-6e2a2934a506.jpg)

**Comment by itkach** [comment]
Looks like [this CSS rule in monobook theme is the culprit](https://github.com/itkach/mwscrape2slob/blob/e01d3e92f0a372ebd0f57390e437a28f9d3c0438/mwscrape2slob/css/mediawiki_monobook.css#L204) - color is explicitly set to black, not sure why. Older versions of russian wikipedia did not use `abbr` for dates (I have one from 2018) so the issue does not manifest itself there.

**Comment by itkach** [comment]
Fixed in https://github.com/itkach/mwscrape2slob/commit/5305cd52cdb2a3fb6164fddd3066541deddae7ca

**Comment by OmlineEditor** [comment]
the problem is not solved. I reinstalled the application on a new device and the problem remained, you did not make changes to the main program on f-droid. please fix the problem

**Comment by itkach** [comment]
The issue is not with the application, it is with dictionary CSS and inline styles in articles, and thus cannot be resolve by reinstalling the app.  It can only be resolved by 

a) getting a new dictionary file compiled with updated version of https://github.com/itkach/mw2slob/, such [as this May 2022 ruwiki](http://ftp.halifax.rwth-aachen.de/aarddict/ruwiki/ruwiki20220520-slob/) 

b) overriding css with user style, as already mentioned. 

> did not make changes to the main program on f-droid
I do not publish to F-Droid and the version published there is not built or packaged by me, so use at your own risk and address F-Droid related issues to https://f-droid.org/en/issues/

**Comment by OmlineEditor** [comment]
the program has its own built-in style. you can change it in case there are problems in other dictionaries and you don't need to use a custom style.
